module.exports = {
  ADD_SUCCESS: "added successfully.",
  UPDATE_SUCCESS: "updated successfully.",
  DELETE_SUCCESS: "deleted successfully.",
  GET_SUCCESS: "get successfully.",
  CONNECTION_DB_SUCCESS: "Connected to MongoDB",
  CONNECTION_DB_ERROR: "Error connecting to MongoDB",
  VALIDATION_FAILED: "Validation failed",
  INVALID_CREDENTIALS: "Credentials dose not match",
  LOGIN_SUCCESS: "Login successfully",
  NO_FILE_UPLOADED: "No file uploaded",
  EMAIL_ALREADY_EXIST: "Email already exists",
  FILE_SIZE_LIMIT: "exceeds the 5 MB size limit.",
  FILE_UPLOAD_ERROR: "Error uploading file",
  ONLY_IMAGE_ALLOWED: "Only image files are allowed!",
  USER_NOT_FOUND: "User not found",
  ACCESS_TOKEN_REQUIRED: "Access token is required",
  INVALID_TOKEN: "Invalid or expired token",
  ERROR_AUTHENTICATING_USER: "Error authenticating user",
  OTP_SUCCESS: "OTP sent successfully",
  PASSWORD_UPDATE_SUCCESSFULLY: "Password updated successfully.",
  OTP_EXPIRE: "OTP has expired. Please request a new OTP.",
  INVALID_OTP: "Invalid OTP",
  OTP_NOT_FOUND: "OTP not found. Please request a new OTP.",
  EMAIL_VERIFICATION: "Email Verification - OTP",
  FAIL_OTP: "Failed to send OTP email",
  CURRENT_PASSWORD: "Current password not matches",
  NEW_PASSWORD_NOT_MATCHES_CURRENT:
    "New password and current password should not be the same",
  COUNTRY_NOT_FOUND: "Country not found",
  INVALID_COUNTRY_ID: "Invalid country ID format",
  STATE_NOT_FOUND: "State not found",
  INVALID_STATE_ID: "Invalid state ID format",
  NO_STATES_FOUND: "No states found for this country",
  NO_CITIES_FOUND: "No cities found for this state",
  EVENT_ID_REQUIRED: "Event ID is required",
  SERVICE_ID_REQUIRED: "Service ID is required",
};
