module.exports = {
  ADD_SUCCESS: "added successfully.",
  UPDATE_SUCCESS: "updated successfully.",
  DELETE_SUCCESS: "deleted successfully.",
  GET_SUCCESS: "get successfully.",
  CONNECTION_DB_SUCCESS: "Connected to MongoDB",
  CONNECTION_DB_ERROR: "Error connecting to MongoDB",
  VALIDATION_FAILED: "Validation failed",
  INVALID_CREDENTIALS: "Credentials dose not match",
  LOGIN_SUCCESS: "Login successfully",
  NO_FILE_UPLOADED: "No file uploaded",
  EMAIL_ALREADY_EXIST: "Email already exists",
  FILE_SIZE_LIMIT: "exceeds the 5 MB size limit.",
  FILE_UPLOAD_ERROR: "Error uploading file",
  ONLY_IMAGE_ALLOWED: "Only image files are allowed!",
  USER_NOT_FOUND: "User not found",
  ACCESS_TOKEN_REQUIRED: "Access token is required",
  INVALID_TOKEN: "Invalid or expired token",
  ERROR_AUTHENTICATING_USER: "Error authenticating user",
};
